### ISSUE TITLE
Annotate training data for DED algorithm

### ISSUE THREAD

**Issue by smomni** [smomni/cranio#24]
Extract old data and annotate each distraction event. Write a script for graphical annotation by utilizing the region widgets implemented in cranio.

### Graphical annotation
Data files are displayed in order. User adds regions to each file and clicks OK to accept the regions. The regions are updated to source data once the selected regions are accepted. User is able to navigate between files (Next / Previous).

### Tasks
- [x] Extract old data
- [x] Write a graphical annotation script
- [ ] Annotate training data

**Comment by smomni** [comment]
Will not be implemented
